courses/urls.py
from django.conf.urls import url

from . import views

urlpatterns =  [
    url(r'^$', views.course_list, name='list'),
    url(r'(?P<course_pk>\d+)/(?P<step_pk>\d+)/$', views.step_detail, name='step'),
    url(r'(?P<pk>\d+)/$', views.course_detail, name='detail'),

    # group named pk followed by 1 or more digits
    # no chevron because it is preceeded by other string
]

learning_site/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^courses/', include(('courses.urls', 'courses'), namespace='courses')),
    path('admin/', admin.site.urls),
    url(r'^$', views.hello_world, name='hello_world'),
]

urlpatterns += staticfiles_urlpatterns()

courses/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    # defines how it will be turned into a string
    def __str__(self):
        return self.title

class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    content = models.TextField(blank=True, default='')
    order = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    # Optional piece - class inside class
    class Meta:
        ordering = ['order',]        

    def __str__(self):
        return self.title

courses/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from .models import Course, Step

# Create your views here.
def course_list(request):
    courses = Course.objects.all()
    # output=', '.join([str(course) for course in courses])
    # return HttpResponse(output)
    email = 'questions@learning_site.com'
    return render(request, 'courses/course_list.html', {'courses': courses, 'email': email   })

def course_detail(request, pk):
    # course = Course.objects.get(pk=pk)
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'courses/course_detail.html', {'course': course })

def step_detail(request, course_pk, step_pk):
    step = get_object_or_404(Step, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/step_detail.html', {'step': step})

learning_site/views.py
from django.shortcuts import render

def hello_world(request):
    return render(request, 'home.html')

courses/templates/courses/course_detail.html
{% extends "layout.html" %}
{% load humanize course_extras %}

{% block title %}
    {{ course.title }}
{% endblock %}    

{% block content %}
    <article>
        <h2>{{ course.title }}</h2>
        {{ course.description|markdown_to_html }}    
        <p>These are {{ course.step_set.count | apnumber }} step{{ course.step_set.count | pluralize }} in this course: {{ course.step_set.all | join:", "}}</p>

        <section>
            {% for step in course.step_set.all %}
                <h3>
                    <a href="{% url 'courses:step' course_pk=step.course.pk step_pk=step.pk %}">{{ step.title }}</a>
                </h3>
                {{ step.description }}
            {% endfor %}
        </section>
    </article>
{% endblock %}

courses/templates/courses/course_list.html
{% extends "layout.html" %}
{% load static %}

{% block static%}<link rel="stylesheet" href="{% static 'courses/css/courses.css' %}">{%endblock%}
{% block title %}Avaiable Courses{% endblock %}

{% block content %}

<div class="cards">
    {% for course in courses %}
        <div class="card">
        <header><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></header>
            <div class="card-copy">
                    <!-- will be very useful for cream -->
                    {% if course.description|wordcount <= 5 %}
                        {{ course.description }}
                    {% else %}
                        {{ course.description|truncatewords:5 }}
                        <a href="{% url 'courses:detail' pk=course.pk %}">Read more</a>
                    {% endif %}
                    <!-- <div>Created on: {{ course.created_at|date:"F j, Y "}}</div>  May 1, 2018 -->
                    <div>Created on: {{ course.created_at|date:"m/d/y"}}</div> 
            </div>
        </div>
    {% endfor %}
    <div>Have questions? Contact us! {{ email|urlize }}</div>
</div>

{% endblock %}

courses/templates/courses/course_nav.html
{% for course in courses %}
<div>
    <a href="{% url 'courses:detail' pk=course.pk %}">
    {{ course.title }}
    </a>
</div>
{% endfor %}

courses/templates/courses/step_detail.html
{% extends "layout.html" %}
{% load course_extras %}

{% block title %} {{ step.title }} - {{ step.course.title }} {% endblock %}

{% block content %}
<article>
    <h2>
        <a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a>
    </h2>
    <h3>{{ step.title }}</h3>
    {% with con=step.content %}
        {{ con|linebreaks }} Content: {{ con|wordcount }} words. Estimated time to complete: {{ con|wordcount|time_estimate }} minute{{ con|wordcount|time_estimate|pluralize }}.
    {% endwith %}
</article>
{% endblock %}

templates/home.html
{% extends "layout.html" %}

{% block title %}Well hello there!{% endblock %}

{% block content %}
    <h1>Welcome!</h1>
{% endblock %}

templates/layout.html
{% load static %}
{% load course_extras %}

<!doctype html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'layout.css' %}" type="text/css">
        {% block static %}{% endblock %}
    </head>
    <body>
        <div class="site-container">
            <div>{% nav_courses_list %}</div>
                <nav>
                    <a href="{% url 'hello_world' %}">Home</a>
                    <a href="{% url 'courses:list' %}">Courses</a>
                </nav>
                <p>Don't miss our latest course, {% newest_course %}!</p>
            {% block content %}{% endblock %}
        </div>
    </body>
</html>